spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderhub_test
    username: orderhub
    password: orderhub
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
